<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS & @V3BOTS
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
*/

$API_KEY = $_ENV['TG_BOT_TOKEN'];
$START_MESSAGE = $_ENV["START_MESSAGE"];
$BOT_USER_NAME = $_ENV["BOT_USER_NAME"];
